export enum appActions {
  ADD_TASK = "ADD_TASK",
  DELETE_TASK = "DELETE_TASK",
  TOGGLE_TASK = "TOGGLE_TASK",
  SET_ERROR = "SET_ERROR",
  SET_FILTER = "SET_FILTER",
  SET_SEARCH_QUERY = "SET_SEARCH_QUERY",
  TOGGLE_STATS = "TOGGLE_STATS",
}
